### ISSUE TITLE
w5500

### ISSUE THREAD

**Issue by safari2** [UIPEthernet/UIPEthernet#1]
Hi.
Will it work with wiznet w5500 & esp8266?
[for example](https://ru.aliexpress.com/item/W5500-Ethernet-LAN-Network-Module-for-Arduino-with-logic-3-3V-5V-New-version-upgrade-W5100/32760767743.html?spm=2114.03010208.3.2.eHxsLv&ws_ab_test=searchweb0_0,searchweb201602_4_10065_10068_10000009_10084_10083_10080_10082_10081_10060_10061_10062_10056_10055_10054_10059_10099_10078_10079_10093_427_10103_10073_10102_10096_10052_10050_10051,searchweb201603_1,afswitch_3&btsid=543a6fa7-a6b0-4467-8fa9-d82dd2bc807f)

**Comment by cassy73** [comment]
Hi!
Maybe, but the wiznet devices and ENC28j60 are very different.
The W5xxx includes fully hardwired, market-proven TCP/IP stack and integrated Ethernet MAC & PHY.
The ENC28j60 doesn't have hardwired TCP/IP stack.
I plan support for RMII PHYs first (LAN8720,DP83848C).

Best Regards
