### ISSUE TITLE
support for generic Powerline adapter

### ISSUE THREAD

**Issue by giorgio80** [UIPEthernet/UIPEthernet#100]
hello guys, 

I would like to try modify the lib for spi Powerline adapter. 

Could I ask you some basic information on driver structure? 

1) does support ipv6 ? 
2) for my understanding you created and upper layer and integrate the existing ENJ2860 driver. I'm right ? can I ask you about a really short architecture overview ?
3) would u suggest to proceed on this road or look for lwip solution instead ?

**Comment by jandrassy** [comment]
what is what you call "spi Powerline adapter"? does it have enc28j60? a doubt that?
- ipv6 is not supported.
- the library is a library over two integrated libraries, a simple enc26j60 library and UIP library and uses for packets only the RAM of enc28j60  to save RAM of MCU. and many use with MCUs with much more RAM then the 2kB of the enc28j60.
- definitively LWIP
