### ISSUE TITLE
Circuit NodeMCU and ENC28J60

### ISSUE THREAD

**Issue by nestorlevi** [UIPEthernet/UIPEthernet#111]
On the CS pin the ENC28J60 has a 10K pull up and the NodeMCU a 12K pull down. This last resistor is necessary for starting. I understand that said transistors in this [circuit](https://raw.githubusercontent.com/UIPEthernet/UIPEthernet/master/hardware/NodeMCU_enc28j60_wiring.PNG) are to not affect the pull down and to obtain a correct start the NodeMCU is initialized.
Seeing in the data sheet the votage ViL max is 0.25xVio, and being Vio = 3.3V -> ViL = 0.825V is the maximum value of the logical zero at the input.
Connecting another 3.8K pull down on D8 (GPIO15) you get the same effect as placing two transistors.

**Comment by jandrassy** [comment]
or even better you some other pin for CS
