### ISSUE TITLE
Wrong #endif when UIP_UDP is disabled

### ISSUE THREAD

**Issue by Nightenom** [UIPEthernet/UIPEthernet#118]
Fix compiler warning caused by wrong #endif position at:
https://github.com/UIPEthernet/UIPEthernet/blob/master/UIPEthernet.cpp#L157-L160
```diff
  }
+#endif
  return rc;
-#endif
}
```

**Comment by jandrassy** [comment]
I know, but it is not worth a commit.. don't use the return value if you disabled UIP_UDP
