### ISSUE TITLE
Question about the BS170 in NodeMCU diagram

### ISSUE THREAD

**Issue by rabbit-aaron** [UIPEthernet/UIPEthernet#121]
Hey I'm new to microcontrollers, what is the purpose of the two BS170 here in the diagram?
https://github.com/UIPEthernet/UIPEthernet/blob/master/hardware/NodeMCU_enc28j60_wiring.PNG

**Comment by jandrassy** [comment]
io 15 must be LOW at boot of esp8266. but you can use some other pin as CS. use Ethernet.init(CS_PIN) to tell the library what pin you wired
