### ISSUE TITLE
UDP ignoring packets?

### ISSUE THREAD

**Issue by pascoea** [UIPEthernet/UIPEthernet#124]
Hey there.  I've been messing with this for a couple days now and can't figure it out.
I'm attempting to use the library to receive/process UDP packets for a lighting controller (e1.31 packets generated by Vixen Lights)

Board is an ESP8266E (Heltec Wifi Kit 8)

Vixen generates a packet for each Universe in the e1.31 configuration, in this instance there are 4 universes.  The sketch processes packets 1 and 2, ignores 3 and 4, then repeats.

I've troubleshot it down to line 374 in UIPUdp.cpp:  if (data->packet_next == NOBLOCK)  For the packets it skips, this test fails, so the uipudp_appcall method essentially ends.

    #include <UIPEthernet.h>
    #include "utility/logging.h"

    EthernetUDP	udp;

    #define UDP_TX_PACKET_MAX_SIZE 800 //increase UDP size

    char packetBuffer[UDP_TX_PACKET_MAX_SIZE]; //buffer to hold incoming packet,

    void setup() {
    	LogObject.begin(74880);
    	uint8_t mac[6] = {0x00,0x01,0x02,0x03,0x04,0x05};
    	Ethernet.begin(mac,IPAddress(10,0,10,51));
    	int success = udp.begin(5568);
        LogObject.uart_send_str(F("initialize: "));
        LogObject.uart_send_strln(success ? "success" : "failed");
    }
 

    void loop() {
    	while(true){
    	  int size = udp.parsePacket();
	  if (size > 0) {
    		int len = udp.read(packetBuffer,UDP_TX_PACKET_MAX_SIZE);
    		//msg[len]=0;
    		LogObject.print(F("Length: "));
    		LogObject.println(len);
    		LogObject.print(F("Data: "));
    		LogObject.println((int)packetBuffer[111]);
    		LogObject.print(F("Univ: "));
    		LogObject.println((int)packetBuffer[114]);
    		}
    	}
    }

Here is a pertinent chunk of the log with "debug" level.
load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
ENC28J60::init DEBUG:csPin = 15
ENC28J60::init DEBUG:miso = 12
ENC28J60::init DEBUG:mosi = 13
ENC28J60::init DEBUG:sck = 14
ENC28J60::init DEBUG:Use SPI lib SPI.begin()
ENC28J60::init INFO: Chip erevid=6 initialization completed.
initialize: success
Enc28J60Network::receivePacket(void) DEBUG:receivePacket [6-28E], next: 292, stat: C0, Packet count: 1 -> OK
Enc28J60Network::receivePacket(void) DEBUG: rxstat OK. receivePkt.size=648
UIPEthernetClass::tick() DEBUG:receivePacket: 255
UIPEthernetClass::tick() DEBUG:readPacket type IP, uip_len: 648
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_buf[34-42]: 7B68
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_packet(255)[42-648]: FFFF
uipudp_appcall(void) DEBUG:udp, uip_newdata received packet: 1, size: 606
UIPEthernetClass::tick() DEBUG:freeing packet: 255
Enc28J60Network::setERXRDPT(void) DEBUG:Set actnextPacketPtr:291
UIPUDP::parsePacket(void) DEBUG:udp parsePacket received packet: 1, size: 606
Enc28J60Network::receivePacket(void) DEBUG:receivePacket [298-52A], next: 52E, stat: C0, Packet count: 2 -> OK
Enc28J60Network::receivePacket(void) DEBUG: rxstat OK. receivePkt.size=658
UIPEthernetClass::tick() DEBUG:receivePacket: 255
UIPEthernetClass::tick() DEBUG:readPacket type IP, uip_len: 658
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_buf[34-42]: 6753
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_packet(255)[42-658]: FFFF
uipudp_appcall(void) DEBUG:udp, uip_newdata received packet: 2, size: 616
UIPEthernetClass::tick() DEBUG:freeing packet: 255
Enc28J60Network::setERXRDPT(void) DEBUG:Set actnextPacketPtr:52D
Length: 606
Data: 11
Univ: 1
Enc28J60Network::receivePacket(void) DEBUG:receivePacket [534-7D0], next: 7D4, stat: C0, Packet count: 1 -> OK
Enc28J60Network::receivePacket(void) DEBUG: rxstat OK. receivePkt.size=668
UIPEthernetClass::tick() DEBUG:receivePacket: 255
UIPEthernetClass::tick() DEBUG:readPacket type IP, uip_len: 668
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_buf[34-42]: 533E
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_packet(255)[42-668]: FFFF
UIPEthernetClass::tick() DEBUG:freeing packet: 255
Enc28J60Network::setERXRDPT(void) DEBUG:Set actnextPacketPtr:7D3
UIPUDP::parsePacket(void) DEBUG:udp parsePacket received packet: 2, size: 616
Length: 616
Data: 11
Univ: 2
Enc28J60Network::receivePacket(void) DEBUG:receivePacket [7DA-262], next: 266, stat: C0, Packet count: 1 -> OK
Enc28J60Network::receivePacket(void) DEBUG: rxstat OK. receivePkt.size=648
UIPEthernetClass::tick() DEBUG:receivePacket: 255
UIPEthernetClass::tick() DEBUG:readPacket type IP, uip_len: 648
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_buf[34-42]: 7A68
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_packet(255)[42-648]: FFFF
uipudp_appcall(void) DEBUG:udp, uip_newdata received packet: 1, size: 606
UIPEthernetClass::tick() DEBUG:freeing packet: 255
Enc28J60Network::setERXRDPT(void) DEBUG:Set actnextPacketPtr:265
UIPUDP::parsePacket(void) DEBUG:udp parsePacket received packet: 1, size: 606
Enc28J60Network::receivePacket(void) DEBUG:receivePacket [26C-4FE], next: 502, stat: C0, Packet count: 2 -> OK
Enc28J60Network::receivePacket(void) DEBUG: rxstat OK. receivePkt.size=658
UIPEthernetClass::tick() DEBUG:receivePacket: 255
UIPEthernetClass::tick() DEBUG:readPacket type IP, uip_len: 658
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_buf[34-42]: 6653
UIPEthernetClass::upper_layer_chksum(uint8_t proto) DEBUG:uip_packet(255)[42-658]: FFFF
uipudp_appcall(void) DEBUG:udp, uip_newdata received packet: 2, size: 616
UIPEthernetClass::tick() DEBUG:freeing packet: 255
Enc28J60Network::setERXRDPT(void) DEBUG:Set actnextPacketPtr:501
Length: 606
Data: 12
Univ: 1

**Comment by jandrassy** [comment]
yes the library stores only two message at once for one port.
I guess if you remove the logging you can read the messages fast enough to process a message before the next arrives.

**Comment by pascoea** [comment]
Thank you for the reply.  Even with having the program do nothing but grab the packet, print a couple characters out of serial, and return to the loop it misses packets.  I'll have to do some more experimentation.

Is the 2 packet a limitation/feature of the uIP library, or the drivers/wrappers?

**Comment by jandrassy** [comment]
the Serial printing is very very slow compared to speed of network, but the MCU is faster then the network. 

the limitation is in UIPUdp. packet_in is message to read, packet_next is one waiting message

**Comment by jandrassy** [comment]
I decided to implement UDP backlog with configurable size in my EthernetENC library

**Comment by pascoea** [comment]
Awesome, look forward to seeing it!  Shoot me a note if there is anything I can do to help.

**Comment by jandrassy** [comment]
but for esp8266 maybe there is a better solution. in esp8266 arduino 3.0, enc28j60 will be supported as additional interface for the ESP8266WiFi library. now it has two interfaces STA and SoftAP. then it will support W5500, enc28j60, PPP...

you could try it https://github.com/esp8266/Arduino/pull/6680

**Comment by jandrassy** [comment]
> I decided to implement UDP backlog with configurable size in my EthernetENC library

done
https://github.com/jandrassy/EthernetENC

**Comment by pascoea** [comment]
Thank you kindly! This (mostly) solved the problem.  I still have some exploring to do, but I was to accomplish what I wanted to.

Note to anyone that finds this:
One of my struggles was an extremely limited receive buffer.  In the enc28j60.h file, the line #define RXSTOP_INIT (0x1FFF-0x1800) only allocates 2k of incoming buffer.  I updated it to 0x1FFF-0x0D00 (~4.75k incoming), this may still not be optimal, just where I arrived at via testing.

**Comment by jandrassy** [comment]
the library moves data from RX packets, to 'TX' area to store them until they are processed by application.
do you have some delays or other code which takes time and doesn't call any function of UIPEthernet? because then the RX queue is not handled. Call some function on some object of UIPEthernet library at least every 250 milliseconds.  Call Ethernet.maintain() if you can't call parsePacket() so frequent.
