### ISSUE TITLE
PlatformIO isn't pulling the 2.0.9 version

### ISSUE THREAD

**Issue by melyux** [UIPEthernet/UIPEthernet#134]
The [PIO library](https://platformio.org/lib/show/1484/UIPEthernet/examples) is stuck on version 2.0.8. The only thing I can think of is that the updated `library.json` with the multiple authors section should have commas between the curly bracket author sections, like in [this example](https://docs.platformio.org/en/latest/librarymanager/config.html#authors).

Right now, there are no commas.

https://github.com/UIPEthernet/UIPEthernet/commit/b9203c78b0f4e33651fb33bfe3e3a9a844888a97#diff-64cc7cdde6789dc1c1c4a6f406cd1ff6a6a00027097788e2d52fc27b0d75502eR12-R29

Could be another problem, I don't know how strict PIO crawler is about the formatting of the JSON, but that's my first guess.

**Comment by jandrassy** [comment]
yes there should be commas

**Comment by melyux** [comment]
It's still not pulling the newer versions after 2.0.8. Looks like it wasn't the comma issue after all.

**Comment by jandrassy** [comment]
> It's still not pulling the newer versions after 2.0.8. Looks like it wasn't the comma issue after all.

maybe ask at platformio

**Comment by 2bndy5** [comment]
@jandrassy @cassy73 v2.0.8 is now showing up, but nothing after that.

I'm writing to tell you I just had a similar experience with the RF24 repo: a missing comma in json required manual re-publishing the lib to PIO registry. However, PIO's new "trusted" lib registry is moving away from crawling existing ("legacy") libs for new releases. You may have to automate publishing this lib yourselves from now on.

**Comment by melyux** [comment]
Any reason for closure?

**Comment by jandrassy** [comment]
is it no fixed? Platformio's Ivan Kravets fixed libarary.json
https://github.com/UIPEthernet/UIPEthernet/pull/145

**Comment by 2bndy5** [comment]
Well, v2.0.9 and v2.0.10 are not available on PIO, but v2.0.11 is.
