### ISSUE TITLE
UDP services, does not work with ESP8266 arduino core above 2.7.4

### ISSUE THREAD

**Issue by NourbakhshRad** [UIPEthernet/UIPEthernet#136]
I am trying to use UIPEthernet with ESP8266 arduino core 3.0.1, my hardware is ESP-12E and ENC28J60 Ethernet shield
Unfortunately UDP services like DHCP, SNMP etc. are not working properly and I had to downgrade my ESP8266 arduino core to 2.7.4
I also tried to change the definitions of conflict but to no avail
Any suggestion?! Thanks

**Comment by NourbakhshRad** [comment]
With this change, my problem was solved!

https://github.com/esp8266/Arduino/commit/08f170510d69423ab58b0fa1edf31b4a5373eba4#diff-2d82230ef328e5fa01af7ef0363e28f757f61016abf8fbb5de06827ec6a006aa

Thanks @jandrassy

**Comment by jandrassy** [comment]
fixed in UIPEthernet GitHub master
