### ISSUE TITLE
UIP_CONNECT_TIMEOUT redefinition

### ISSUE THREAD

**Issue by luzrain** [UIPEthernet/UIPEthernet#138]
How I can redefine UIP_CONNECT_TIMEOUT flag? I tried define `#define UIP_CONNECT_TIMEOUT 3` in main sketch ino file, but it does not give any effect.

**Comment by jandrassy** [comment]
change it in uipethernet-conf.h
or
> Arduino IDE doesn't have the possibility to set defines for a sketch (For example Sloeber has it). As some workaround to set the defines for different boards for Arduino IDE, you can create a file boards.local.txt next to boards.txt file in hardware package. Set build.extra_flags for individual boards. For example for Mega you can add to boards.local.txt this line with -D options to define the macros:
>`mega.build.extra_flags= -DUIP_CONF_MAX_CONNECTIONS=6 -DUIP_CONNECT_TIMEOUT=3`
