### ISSUE TITLE
"client.connected()" always return true

### ISSUE THREAD

**Issue by ostium** [UIPEthernet/UIPEthernet#15]
Hello, 

After I do a client.stop(), client.connected() return always true. It's normal?

How can I know if client is disconnected?

Thanks for the help.

**Comment by cassy73** [comment]
Hi!

This doesn't normal.
After You call client.stop, client.connected must return 0.
If You use big device (Not UNO.) please set ACTLOGLEVEL to LOG_DEBUG_V3, and send me the log  messages.

Best Regards

**Comment by jandrassy** [comment]
@ostium, is this still a valid issue?
