### ISSUE TITLE
single port multi connection

### ISSUE THREAD

**Issue by snnzdmr** [UIPEthernet/UIPEthernet#158]
Hello ,
I have 4 ports in total.

EthernetServer server_1 = EthernetServer(1000);
EthernetServer server_2 = EthernetServer(1001);
EthernetServer server_3 = EthernetServer(1002);
EthernetServer server_4 = EthernetServer(1003);

If I connect to the same port with 2 different clients, uipethernet accepts both connections.
Is there any way to prevent this ?
Only 1 client should be connected to each port

note: uipethernet lib 2.0.10

**Comment by JAndrassy** [comment]
use server.accept(), not server.available()
https://www.arduino.cc/reference/en/libraries/ethernet/server.accept/

**Comment by snnzdmr** [comment]
yes I am using "accept()".
I just stop the code after "server_1.begin()" is done
but even if I don't call the "accept()" function in the code, the same port accepts both connections.
![uip](https://user-images.githubusercontent.com/16215260/175891714-2f9c9636-3f5a-4c4b-9ff2-b1f27f913185.jpg)

**Comment by JAndrassy** [comment]
you have to accept() and then stop()

**Comment by snnzdmr** [comment]
ok.thank you for your help.
