### ISSUE TITLE
Arduino Uno R4 minima [solved]

### ISSUE THREAD

**Issue by shpaq22** [UIPEthernet/UIPEthernet#164]
Hello, 

I'm using this library for Arduino Uno R3 with the ENC28J60 Ethernet module, and it works very well. 

Now, I've created a new setup with the latest hardware, using Arduino Uno R4 minima. Unfortunately, it doesn't work, and I'm missing declarations for SPI_MOSI, SPI_MISO, SPI_SCK, and SS.

Can you provide guidance on how to add these declarations to the library?

=======================================
#error "Not defined SPI_MOSI!"
#error "Not defined SPI_MISO!"
#error "Not defined SPI_SCK!"

**Comment by JAndrassy** [comment]
use the EthernetENC library

**Comment by shpaq22** [comment]
Thanks a lot! It's working :)
