### ISSUE TITLE
Get TCP connection parameters

### ISSUE THREAD

**Issue by George-JL** [UIPEthernet/UIPEthernet#18]
UIPEthernet library works great!

I am looking for a way to get details of the open TCP connection. Namely
```EthernetClient client = Server.available();
 if (client) {
  // Here, I need to get client IP address (server socket's remote IP)

}
```
Is there any way how to get it? How to modify the source to get it working?

**Comment by jandrassy** [comment]
duplicate of https://github.com/UIPEthernet/UIPEthernet/issues/32

I know that this was first, but that is not important.

**Comment by jandrassy** [comment]
done
