### ISSUE TITLE
Possible integration of Wiznet W5500 / Wiz550io

### ISSUE THREAD

**Issue by asetyde** [UIPEthernet/UIPEthernet#19]
Hi , I ve many problems wit not updated library of wiznet of 5500 , this board is important because is a few models wit a low price can give a macaddress inside board .

I ask if someone can help me to integrate on this library , this board .
I see that w5100 is compatible , w5500 is not so different but has Mac and more powerful  chip.

Ref of wiznet libraries and wiki 👍 
https://github.com/embeddist/WIZ_Ethernet_Library-IDE1.6.x
http://wizwiki.net/wiki/doku.php?id=products:wiz550io:start

**Comment by zoomx** [comment]
"Compatible with Wiznet W5100 Ethernet library API" mean that you can use the same functions not that the library works with a Wiznet W5100. This is a libary for ENC28j60.

**Comment by asetyde** [comment]
ok many thanks !
