### ISSUE TITLE
byte-order on Teensy

### ISSUE THREAD

**Issue by manitou48** [UIPEthernet/UIPEthernet#22]
Byte-order problem on Teensy 3.2 ?? see discussion at
https://forum.pjrc.com/threads/47791-Teensy-3-2-ENC28J60-Strange-behavior

**Comment by fpistm** [comment]
Hi,
same issue with the [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32).

Issue discussed also here: https://github.com/stm32duino/Arduino_Core_STM32/issues/132

**Comment by fpistm** [comment]
I've submitted a patch for this. See #26 https://github.com/UIPEthernet/UIPEthernet/pull/26/commits/a0a4789d5abadad15ff6406c3aedc5178f2af445

**Comment by cassy73** [comment]
Arduino_Core_STM32 support added.
Endianness configuration changed.
