### ISSUE TITLE
This library is not working: WARNING: Don't free NOBLOCK handle

### ISSUE THREAD

**Issue by Dravon5X** [UIPEthernet/UIPEthernet#25]
Hi

I have issue that this library is not working at all. I have set every IP manually (ip, gateway, dns, mask) and client.connect() is returning -5 and in debug log I see this:
```
ENC28J60::init INFO: Chip erevid=6 initialization completed.
MemoryPool::freeBlock(memhandle handle) WARNING: Don't free NOBLOCK handle
MemoryPool::freeBlock(memhandle handle) WARNING: Don't free NOBLOCK handle
MemoryPool::freeBlock(memhandle handle) WARNING: Don't free NOBLOCK handle
MemoryPool::freeBlock(memhandle handle) WARNING: Don't free NOBLOCK handle
MemoryPool::freeBlock(memhandle handle) WARNING: Don't free NOBLOCK handle
MemoryPool::freeBlock(memhandle handle) WARNING: Don't free NOBLOCK handle
```
Edit:
I got it working when I change this
`const char server[] PROGMEM = "domain.com";`
to this
`const char server[] = "domain.com";`

Can you please handle this and write to debug log message that PROGMEM can't be used, or fix code to be able to work with PROGMEM?

**Comment by cassy73** [comment]
Hi!

If You want store hostname to flash, please try it with PSTR function.
example:
if (client.connect(PSTR("server.local"),5000))

Best Regards!

**Comment by jandrassy** [comment]
the connect function doesn't take progmem string as parameter
