### ISSUE TITLE
Change CS on ESP8266

### ISSUE THREAD

**Issue by jcalcocer** [UIPEthernet/UIPEthernet#28]
Hi, i want to change the pin  ENC28J60_CONTROL_CS SS to  ENC28J60_CONTROL_CS 5 but i not have idea to how i do, the pin SS is the 15 but this pin i already put to ground so i want tu use the pin 5 for CS.

thanks.

**Comment by cassy73** [comment]
Hi!

You can define ENC28J60_CONTROL_CS at the beginning of the file utility/Enc28J60Network.h,
before line "#if !defined(ENC28J60_CONTROL_CS)".

example:
#define ENC28J60_CONTROL_CS D1

Best regards
