### ISSUE TITLE
Dhcp error with ESP8266

### ISSUE THREAD

**Issue by marso0702** [UIPEthernet/UIPEthernet#3]
Hello,
i found a problem in the dhcp.cpp in line 343:
if( *((uint32_t*)_dhcpDhcpServerIp) == 0

The ESP8266 seams to have a Problem with that and crashes.
I Changed it to
if( IPAddress(_dhcpDhcpServerIp) == IPAddress(0,0,0,0) || 
and that it works.

Kind Regards
Martin

**Comment by cassy73** [comment]
Thank You.
The error fixed.

Best Regards
