### ISSUE TITLE
Blue Pill wiring problem

### ISSUE THREAD

**Issue by hsamonik** [UIPEthernet/UIPEthernet#35]
The wiring shown in the picture in hardware doesn´t work
Right Connection
A4-->CS
A5--> SCK
A6-->SO
A7-->SI

**Comment by vanbwodonk** [comment]
I agree with this. I think wiring in the hardware folder is miss information from maple mini wiring 
![image](https://user-images.githubusercontent.com/5450820/57277448-60232280-70ce-11e9-81af-532e1cebeb26.png)

**Comment by jandrassy** [comment]
yes, @hsamonik has the right connections

**Comment by jandrassy** [comment]
I corrected the picture
