### ISSUE TITLE
connect esp8266 without bs170

### ISSUE THREAD

**Issue by bramnyadewi007** [UIPEthernet/UIPEthernet#37]
its not a issue actualy,  just i've got the enc working for esp8266 on nodemcu/wemos mini without bs170. im using D1(nodemcu/wemos mini) or gpio5 as CS pin.
and some change to library Enc28J60Network.h
and set pin gpio 5 to high after ethernet.begin();
below is the change ive made.
thx..

#if !defined(ENC28J60_CONTROL_CS)
 #if defined(ESP8266)
 #define ENC28J60_CONTROL_CS     5
  #endif
    #if defined(__AVR__) || defined(__RFduino__)
   //#if defined(__AVR__) || defined(ESP8266) || defined(__RFduino__)

**Comment by jandrassy** [comment]
it will be solved with Ethernet.init(cspin) in https://github.com/UIPEthernet/UIPEthernet/pull/45
