### ISSUE TITLE
setting UIP_CONF_UDP to 0 or commenting it out generates compilation errors

### ISSUE THREAD

**Issue by pabloandresm** [UIPEthernet/UIPEthernet#5]
The utility/uipethernet-conf.h says:
/* for UDP
 * set UIP_CONF_UDP to 0 to disable UDP (saves aprox. 5kb flash) */

Commenting it out, or redefining it to 0 generates compilation errors, like:

libraries\UIPEthernet/Dhcp.h:139: undefined reference to `UIPUDP::UIPUDP()'

**Comment by cassy73** [comment]
The error is fixed.
Please try it with actual code.

**Comment by consolacion** [comment]
I am using the latest version as far as I know (2.0.4)
and it doesnt seem fixed:
Arduino: 1.8.3 (Linux), Board: "Arduino/Genuino Uno"

/tmp/cc8rxrWd.ltrans1.ltrans.o: In function `setup':
/home/me/Arduino/enc28j60MQTT_v2/enc28j60MQTT_v2.ino:55: undefined reference to `UIPEthernetClass::begin(unsigned char const*)'
