### ISSUE TITLE
Is this repository abandoned? No commits for over a year now...

### ISSUE THREAD

**Issue by marcoacarvalho** [UIPEthernet/UIPEthernet#55]

**Comment by jandrassy** [comment]
cassy73 seems to be the only one with write access. I wrote an e-email a week ago to e-mail address on the profile, but no answer. In past there were long delays between commits. 
In my fork the pull requests are merged

**Comment by marcoacarvalho** [comment]
Thank you @jandrassy, I merged your fork into mine.
Will be nice if @cassy73  give you write access, you're doing a great job.
