### ISSUE TITLE
Teensy 2.0, it's working?

### ISSUE THREAD

**Issue by chinch2** [UIPEthernet/UIPEthernet#58]
Hi, I just want to send GET requests to a web server using the ENC28J60 and a teensy 2.0, does this library work for that just like it is right now? or I have to change some senteces in the code? Thank you!

**Comment by jandrassy** [comment]
Teensy should work. You can make some adjustments in `Arduino/libraries/UIPEthernet/utility/uipethernet-conf.h` if you need more connections or doesn't need UDP
