### ISSUE TITLE
I can only connect 4 times with enc28j60

### ISSUE THREAD

**Issue by ErencanErkarakas** [UIPEthernet/UIPEthernet#66]
I can only connect 4 times with enc28j60 and then try to connect again for a while.

**Comment by jandrassy** [comment]
do you close the connection?

**Comment by ErencanErkarakas** [comment]
Serial.println("OKUDU");
  while (true)
  {
    if (!client.connect(IPAddress(192, 168, 1, 111), 123)) {
      delay(100);
      Serial.println("Baglanmadi");
 }
    else{
      break;
    }

  }
  /*if () {
    Serial.println("Baglanmadi");

    }*/
  Serial.println("Baglanti Kuruldu");


  client.println(rfid);
  Serial.println(rfid);
  getmessage();
  ServerDisconnect();
}

**Comment by ErencanErkarakas** [comment]
maximum connection count =4

**Comment by ErencanErkarakas** [comment]
@jandrassy

**Comment by jandrassy** [comment]
you don't call client.stop()

**Comment by ErencanErkarakas** [comment]
void ServerDisconnect() {
  Serial.println("Serverdan Cikis Yapildi");
  client.stop();
}

**Comment by ErencanErkarakas** [comment]
@jandrassy

**Comment by jandrassy** [comment]
you don't need to '@jandrassy` me. I get a notification on every change in the repository.
the TCP connection is closed if booth sides close the connection (or timeout). does the server close the connection? do you need to open the connection every time? can't you leave the connection open?

In [my project](https://github.com/jandrassy/Regulator) I have 3 servers (telnet, web, sketch upload), modbus client, upnp client, http client, Blynk on 6 connections

**Comment by ErencanErkarakas** [comment]
I just want to connect to a single server with this server can only connect 4 times

**Comment by jandrassy** [comment]
the connection is not free until the other side closes the socket too. the library doesn't abort the connection.

**Comment by ErencanErkarakas** [comment]
I closed the connection by the server and the result is not changed Are you using the sample code, or would you suggest another library?

**Comment by jandrassy** [comment]
do you use version 2.0.7?

**Comment by ErencanErkarakas** [comment]
latest version.
