### ISSUE TITLE
ESP32 support. Wiring?

### ISSUE THREAD

**Issue by VanKurt** [UIPEthernet/UIPEthernet#67]
Does this library work with the ESP32? How should it be wired?

**Comment by jandrassy** [comment]
yes it does. wire it to SPI

**Comment by VanKurt** [comment]
But how can I control e.g. which pin shall be used for chip select?

**Comment by jandrassy** [comment]
Ethernet.init(CS_PIN)

**Comment by VanKurt** [comment]
Awesome. Thanks a lot!

**Comment by frederic-bonjour** [comment]
I have a ESP32-WROOM-32 NodeMCU. Are the transistors needed, as mentioned on the schematics for the ESP8266 NodeMCU?

**Comment by jandrassy** [comment]
no. the transistors handle the state of the esp8266 boot pin io 15 to be LOW at boot, because it is the SPI SS pin which should be HIGH.
on esp32 this is not a problem.

**Comment by frederic-bonjour** [comment]
Thank you very much, I'll try that.

**Comment by frederic-bonjour** [comment]
It tells me:
> Failed to configure Ethernet using DHCP
Ethernet shield was not found.  Sorry, can't run without hardware. :(

**Comment by frederic-bonjour** [comment]
My mistake: it works! Thank you so much! :)

**Comment by frederic-bonjour** [comment]
And is there a way to make OTA updates working via Ethernet?

**Comment by jandrassy** [comment]
copy one of the OTA libraries of the esp32 core and in the copy replace "WiFi" with "Ethernet".
Only the mDns part will not work, so the Arduino IDE will not show a network port. because UDP.beginMulticast() is not implemented in UIPEthernet yet

**Comment by frederic-bonjour** [comment]
OK, thanks!
But how do I update the sketch if the Arduino IDE does not allow me to select the network port?

**Comment by jandrassy** [comment]
the esp8266 has a HTTPUpdateServer library, which (now I see) is missing in esp32 package. 
the HTTPUpdate library checks a web server for new bin file.
for ArduinoOTA upload from command line is possible

**Comment by frederic-bonjour** [comment]
I'm trying to make HTTP updates working. Still have a checksum error, but I keep on searching this way ;) Thank you again for your answers and your time!
