### ISSUE TITLE
UIPEthernet and ESP32

### ISSUE THREAD

**Issue by frederic-bonjour** [UIPEthernet/UIPEthernet#68]
Hello,

Is there anyone who achieved to make an ESP32 work with the ENC28J60 module?
Could you post a schematics that works?

Thank you very much, guys! Have a nice day! :)

**Comment by jandrassy** [comment]
https://github.com/UIPEthernet/UIPEthernet/issues/67

**Comment by frederic-bonjour** [comment]
Thanks!
