### ISSUE TITLE
ESP32 Problem

### ISSUE THREAD

**Issue by gorkembendin** [UIPEthernet/UIPEthernet#70]
Hi,
I tried to use this library on my project but I've faced with the problem below;

**Steps:**
- Installed UIPEthernet library using Arduino IDE.
- Included UIPEthernet.h file.
- Tried to compile project and had the error below.

**Problem:** Arduino\libraries\UIPEthernet/UIPServer.h:45:3: error: invalid abstract return type 'UIPClient' UIPClient available();

Could you please guide me about using this library?

**Comment by jandrassy** [comment]
use esp32 arduino package 1.0.1. 1.0.2 has a compatibility issues not only with UIPEthernet
https://github.com/espressif/arduino-esp32/commit/9a9ff622166149da30dd13a81485184617c56387#commitcomment-33292990
