### ISSUE TITLE
ESP32 1.0.3-rc1 Arduino IDE 1.8.9 problem

### ISSUE THREAD

**Issue by vallesolucoes** [UIPEthernet/UIPEthernet#72]
**### someone help me please**

`Arduino: 1.8.9 (Windows 10), Placa:"ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 80MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from D:\arduino-1.8.9-windows\arduino-1.8.9\portable\sketchbook\libraries\UIPEthernet/UIPEthernet.h:42:0,

                 from D:\arduino-1.8.9-windows\arduino-1.8.9\portable\sketchbook\libraries\UIPEthernet\examples\TcpServer\TcpServer.ino:37:

D:\arduino-1.8.9-windows\arduino-1.8.9\portable\sketchbook\libraries\UIPEthernet/UIPServer.h:49:3: error: invalid abstract return type 'UIPClient'

   UIPClient available();

   ^

In file included from D:\arduino-1.8.9-windows\arduino-1.8.9\portable\sketchbook\libraries\UIPEthernet/UIPEthernet.h:41:0,

                 from D:\arduino-1.8.9-windows\arduino-1.8.9\portable\sketchbook\libraries\UIPEthernet\examples\TcpServer\TcpServer.ino:37:

D:\arduino-1.8.9-windows\arduino-1.8.9\portable\sketchbook\libraries\UIPEthernet/UIPClient.h:75:9: note:   because the following virtual functions are pure within 'UIPClient':

   class UIPClient : public Client {

         ^

In file included from D:\arduino-1.8.9-windows\arduino-1.8.9\portable\packages\esp32\hardware\esp32\1.0.3-rc1\cores\esp32/Arduino.h:151:0,

                 from sketch\TcpServer.ino.cpp:1:

D:\arduino-1.8.9-windows\arduino-1.8.9\portable\packages\esp32\hardware\esp32\1.0.3-rc1\cores\esp32/Client.h:31:17: note: 	virtual int Client::connect(IPAddress, uint16_t, int)

     virtual int connect(IPAddress ip, uint16_t port, int timeout) =0;

                 ^

D:\arduino-1.8.9-windows\arduino-1.8.9\portable\packages\esp32\hardware\esp32\1.0.3-rc1\cores\esp32/Client.h:32:17: note: 	virtual int Client::connect(const char*, uint16_t, int)

     virtual int connect(const char *host, uint16_t port, int timeout) =0;

                 ^

D:\arduino-1.8.9-windows\arduino-1.8.9\portable\sketchbook\libraries\UIPEthernet\examples\TcpServer\TcpServer.ino: In function 'void loop()':

TcpServer:79:48: error: cannot allocate an object of abstract type 'UIPClient'

   if (EthernetClient client = server.available())

                                                ^

TcpServer:79:22: error: cannot declare variable 'client' to be of abstract type 'UIPClient'

   if (EthernetClient client = server.available())

                      ^

exit status 1
cannot allocate an object of abstract type 'UIPClient'

Este relatório teria mais informações com
"Mostrar a saida detalhada durante a compilação"
opção pode ser ativada em "Arquivo -> Preferências"
`

**Comment by jandrassy** [comment]
the ESP32 arduino core diverted from Arduino compatibility. create an issue there
