### ISSUE TITLE
Cannot use with ST-CORE

### ISSUE THREAD

**Issue by nopnop2002** [UIPEthernet/UIPEthernet#74]
Hello.

I use Blue Pill + ST-Core Ver1.6.1 + UIPEthernet2.0.7 + ENC28J60.

![ST-Core](https://user-images.githubusercontent.com/6020549/61988760-d3e72280-b060-11e9-9fbd-a1643f2636da.jpg)

![UIPEthernet](https://user-images.githubusercontent.com/6020549/62001141-3d7c3500-b124-11e9-81b9-5e046174b629.jpg)

Wireing is:
PA4:CS
PA5:SCK
PA6:SO
PA7:SI

I tested this sketch:
But Internet.begin become fail.

![enc28j60](https://user-images.githubusercontent.com/6020549/61988729-4d324580-b060-11e9-9242-29b49b219b59.jpg)

Do you have any help?

	#include <UIPEthernet.h> // For ENC28J60

	void setup() {
	  byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED }; 
	   
	  Serial.begin(115200);
	  while (!Serial) {
	    ; // wait for serial port to connect. Needed for native USB port only
	  }
	  Serial.println("Start Ethernet.begin");
	  if (!Ethernet.begin(mac) ) {
	    Serial.println("Ethetnet begin fail");
	    while(1) {}
	  }
	  Serial.print("localIP: ");
	  Serial.println(Ethernet.localIP());
	  Serial.print("subnetMask: ");
	  Serial.println(Ethernet.subnetMask());
	  Serial.print("gatewayIP: ");
	  Serial.println(Ethernet.gatewayIP());
	  Serial.print("dnsServerIP: ");
	  Serial.println(Ethernet.dnsServerIP());

	  for (byte thisByte = 0; thisByte < 4; thisByte++) {
	    // print the value of each byte of the IP address:
	    Serial.print(Ethernet.localIP()[thisByte], DEC);
	    if (thisByte != 3) Serial.print("-");
	  }

	}

	void loop() {
	}

**Comment by jandrassy** [comment]
use Ethernet.init(pin) to set the CS pin

**Comment by nopnop2002** [comment]
I changed wire.

```
ENC28J60    STM32F103
----------------------
GND         GND
3V3         3V3
RESET       PullUp
SCK         PA5(SCK)
SO          PA6(MISO)
SI          PA7(MOSI)
INT         PA4(CS)
CS          PullDown
WCL         N/C
CLKOUT      N/C
```

But Ethetnet begin fail.

**Comment by jandrassy** [comment]
I didn't write anything about wiring.
in code use `Ethernet.init(PA4);` to use PA4 as the CS pin. without it the library doesn't know what pin did you wire as CS

**Comment by nopnop2002** [comment]
Thank you for your reply.
I changed the sketch:

```
#include <UIPEthernet.h> // For ENC28J60

void setup() {
  byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED }; 
   
  Serial.begin(115200);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
  Serial.println("Start Ethernet.begin");
  Ethernet.init(PA4);
  if (!Ethernet.begin(mac) ) {
    Serial.println("Ethetnet begin fail");
    while(1) {}
  }
  Serial.print("localIP: ");
  Serial.println(Ethernet.localIP());
  Serial.print("subnetMask: ");
  Serial.println(Ethernet.subnetMask());
  Serial.print("gatewayIP: ");
  Serial.println(Ethernet.gatewayIP());
  Serial.print("dnsServerIP: ");
  Serial.println(Ethernet.dnsServerIP());

  for (byte thisByte = 0; thisByte < 4; thisByte++) {
    // print the value of each byte of the IP address:
    Serial.print(Ethernet.localIP()[thisByte], DEC);
    if (thisByte != 3) Serial.print("-");
  }
}

void loop() {
}
```

Conection:

```
ENC28J60    STM32F103
----------------------
GND         GND
3V3         3V3
RESET       PullUp
SCK         PA5(SCK)
SO          PA6(MISO)
SI          PA7(MOSI)
INT         N/C
CS          PA4(CS)
WCL         N/C
CLKOUT      N/C
```

But Ethetnet begin fail.
The Ethernet module works fine with UNO.

**Comment by jandrassy** [comment]
try some other pin as CS

**Comment by jandrassy** [comment]
I retested it with STM32 core 1.8.0. No problems.
