### ISSUE TITLE
Incoming TCP Connection Fails first time after stopping an outgoing TCP Connection

### ISSUE THREAD

**Issue by Joe2019** [UIPEthernet/UIPEthernet#75]
Hi, I am struggling with a problem which I suspect may be in the library but I am looking for advice

UIPEthernet version 2.0.7 
Hardware Arduino NANO 
I have an Arduino NANO connected to ENC28J60..   
I can connect to the NANO (incoming connection ) via TCP  no problem..  but I also want the NANO to be able to originate a connection to another web server occasionally.  This works fine as well, but after closing this connection, the Next time I try to connect to the NANO with an incoming connection , the NANO does not respond  - i.e. server.available() returns null and the connection fails.  A second attempt is always successful. 
This scenario is repeatable 100% of the time  
It makes no difference if the incoming connection is 1 or 2 seconds after the outgoing connection is closed  or 30+ seconds. It seems as if something is not reset properly after the client.stop() 

I have attached
 some code below..    for testing  

Sending a HTTP POST with the parameters  TST=0   the NANO will respond with HTTP 200 OK 
After 1 minute the NANO  sends a HTTP POST (CMD=12) to 192.168.1.104 and receives  a HTTP 200 reply (Command Successful)  
Now Sending a HTTP POST to the NANO will fail the first attempt..

[Test_Web.zip](https://github.com/UIPEthernet/UIPEthernet/files/3517323/Test_Web.zip)

**Comment by jandrassy** [comment]
you use the Client object returned by Server to connect to other server. use two separate Client variables
