### ISSUE TITLE
Full duplex support

### ISSUE THREAD

**Issue by santiago-vanoli-1975** [UIPEthernet/UIPEthernet#79]
Hi, is full duplex supported in this library? What modifications should I do on the code for it to work?
Thanks in advance, 
Santiago

**Comment by jandrassy** [comment]
full duplex is not set

from the datasheet

> DUPLEX MODE CONFIGURATION AND NEGOTIATION The  ENC28J60  does  not  support  automatic  duplex negotiation.  If  it  is  connected  to  an  automatic  duplex negotiation enabled network switch or Ethernet controller,  the  ENC28J60  will  be  detected  as  a  half-duplexdevice.  To  communicate  in  Full-Duplex  mode,  theENC28J60  and  the  remote  node  (switch,  router  or Ethernet  controller)  must  be  manually  configured  for full-duplex operation.

> ENC28J60  operates  in  Half-Duplex  mode  whenMACON3.FULDPX = 0 and PHCON1.PDPXMD = 0
