### ISSUE TITLE
DHCP timeout?

### ISSUE THREAD

**Issue by alxferraz** [UIPEthernet/UIPEthernet#9]
How can I set a timeout while trying to connect with DHCP?  I noticed there is one but I would like it shorter. Thanks in advance!

**Comment by JZ-SmartThings** [comment]
In the UIP library folder, take a look at DHCP.h, go to the bottom and look 5 lines up. I'm surprised that you have DHCP working at all. This has never worked for me.

**Comment by cassy73** [comment]
Hi!

The DHCP code already modified but doesn't tested.
Publication coming soon.

Best Regards

**Comment by JZ-SmartThings** [comment]
Happy to test if you have a preview ready somewhere. Thanks for the changes!

**Comment by cassy73** [comment]
You can set timeouts in dhcp.h file.
#define DHCP_TIMEOUT            60000
#define DHCP_RESPONSE_TIMEOUT   4000
The values are in milliseconds.

Tested TCPCLIENT.INO example with ESP8266.

Best Regards

**Comment by alxferraz** [comment]
Thank You very much guys!

**Comment by cassy73** [comment]
Hi!

Please try it, and if working properly then close this issue.

Best Regards
