### ISSUE TITLE
Support for ENC424J600

### ISSUE THREAD

**Issue by felix900006** [UIPEthernet/UIPEthernet#91]
Is there a way to add Support for the ENC424J600 Chip?
Or what has to be changed to make it working with the  #ENC424J600 Chip? #

**Comment by jandrassy** [comment]
the handling of ENC424J600 is very similar, yet different in details. adding handling of this details would make the library larger.
you could fork the library, open the datasheet for ENC424J600 and modify the details in Enc28J60Network.cpp and surrounding.
