### ISSUE TITLE
ESP8266 TCP client not correctly works.

### ISSUE THREAD

**Issue by cyberpablis** [UIPEthernet/UIPEthernet#94]
I'm trying to send and receive binary data packets using TCP client but is not efficiently working. A lot of packets lost and sometimes, the data sent not really sent. The size of the each data packet is 500 bytes.
What's can be wrong?

My hardware is made with ESP8266 and ENC28J60 shield.

**Comment by jandrassy** [comment]
is the WiFi off? they both need 150 mA while transmiting

**Comment by cyberpablis** [comment]
WiFI is off
Transmission is through ENC28J60 using EthernetClient object

**Comment by cyberpablis** [comment]
This is my code:

#include <ESP8266WiFi.h>
#include <UIPEthernet.h>

EthernetClient tETHClient;
uint8_t        vMAC[6] = { 0x40, 0x23, 0x33, 0x11, 0x10, 0x02 };
uint8_t        Buf[500];

void setup()
  {
  WiFi.mode(WIFI_OFF); 
  delay(1);       
  // Wait for DHCP request.
  while (Ethernet.begin(vMAC) == 0);
  }

void loop()
  {
  // Stay connected to remote server socket.
  if (!tETHClient.connected())
    if (tETHClient.connect("190.61.77.251", 3005);

  // When a packet must be sended ... 
  tETHClient.write(Buf, sizeof(Buf));
  tETHClient.flush();

  // To Check if a packet incoming...
  while (tETHClient.available() > 0) 
    if (tETHClient.read(Paq.tfBuf, sizeof(Paq.tfBuf)) == sizeof(Paq.tfBuf))
      {
      // Process packet...
     
       
      }
  }

**Comment by cyberpablis** [comment]
#include <ESP8266WiFi.h>
#include <UIPEthernet.h>

EthernetClient tETHClient;
uint8_t        vMAC[6] = { 0x40, 0x23, 0x33, 0x11, 0x10, 0x02 };
uint8_t        Buf[500];

void setup()
  {
  WiFi.mode(WIFI_OFF); 
  delay(1);       
  // Wait for DHCP request.
  while (Ethernet.begin(vMAC) == 0);
  }

void loop()
  {
  // Stay connected to remote server socket.
  bool b = tETHClient.connected();
  if (!b) b = tETHClient.connect("190.61.77.251", 3005);
  
  if (b)
    {
    // When a packet must be sended ... 
    tETHClient.write(Buf, sizeof(Buf));
    tETHClient.flush();

    // To Check if a packet incoming...
    while (tETHClient.available() > 0) 
      if (tETHClient.read(Paq.tfBuf, sizeof(Paq.tfBuf)) == sizeof(Paq.tfBuf))
        {
        // Process packet...
     
       
        }
    }
  }

**Comment by jandrassy** [comment]
I think you put more load on the library then it can handle. The library is written for small MCUs and uses only the 2kB RAM of the enc28j60 to store incoming packets. This takes the space normally to send packets.
you should try this https://github.com/esp8266/Arduino/pull/6680

**Comment by cyberpablis** [comment]
Tks for your answer. 
I will try to implement the enc28j60 interrupt to intercept incoming packets

**Comment by cyberpablis** [comment]
I resized the buffer to 50 bytes and nothing.
The library has a problem and do not properly works

**Comment by jandrassy** [comment]
> I resized the buffer to 50 bytes and nothing.
> The library has a problem and do not properly works

500 for receive is good. but try to send only 250 bytes at once.

yes it has a problem, the concept of the library doesn't allow receive and send so much so fast. it was not made for fast MCU with so much memory.

**Comment by jandrassy** [comment]
I fixed a bug. could you please try the Git version to see if it solved your problem?

**Comment by cyberpablis** [comment]
Excellent! It works!!!! Thanks a lot

Enviado desde mi iPhone

**Comment by cyberpablis** [comment]
Hi.

I use a UIPEthernet TCP client on a ESP8266 to connect a server socket in a PC, and send periodic packets.
If from Windows, I deactivate the network card on which it receives the packets and activate it again, the device freezes. I thought it would stay blocked until after the TCP connection timeout, but not, it freezes forever.

What I can be doing wrong?

Best regards


Enviado desde mi iPhone

**Comment by jandrassy** [comment]
> Hi. I use a UIPEthernet TCP client on a ESP8266 to connect a server socket in a PC, and send periodic packets. If from Windows, I deactivate the network card on which it receives the packets and activate it again, the device freezes. I thought it would stay blocked until after the TCP connection timeout, but not, it freezes forever. What I can be doing wrong? Best regards 

did you try to set UIP_CONNECT_TIMEOUT in uipethernet-conf.h?

**Comment by cyberpablis** [comment]
I've tried, but the ESP8266 stays frozen forever, like it's in an infinite loop. does not respond, does not refresh the display, nothing.

Enviado desde mi iPhone
